### PR TITLE
Updated Minecraft server version

### PR DESCRIPTION
**Pull request by danielnv18**
If you try to connect Minecraft to this version of the server, it'll tell you that the server is outdated

### CODE REVIEW

**Comment by FrenchBen** [comment]
Can you squash your commits and also sign them?
See: https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by 4-20ma** [comment]
Bumping @danielnv18 to squash commits/sign them. I would also like the Minecraft version updated. Thanks.

**Comment by danielnv18** [comment]
sorry I forgot about his. Give me 5 mins and I will update it

**Comment by danielnv18** [comment]
@FrenchBen I created a different PR #10

**Pull request closed without merging**
