### PR TITLE
update to new version

### PR DESCRIPTION
**Pull request by ls-endurance**

### CODE REVIEW

**Comment by FrenchBen** [comment]
Looks like the file doesn't exist - https://s3.amazonaws.com/Minecraft.Download/versions/1.13/minecraft_server.1.13.jar

**Comment by ls-endurance** [comment]
No it doesn't. Its not my AWS so i could not upload the new minecraft jar to the s3 bucket, but whoever owns it could?

Or should I just make a new public S3 bucket with the newest jar?

**Comment by FrenchBen** [comment]
@ls-endurance It's the upstream download location for Minecraft server, not something we should maintain - if there's a new location to download from, please update the Dockerfile to reflect that 🙏

**Comment by FrenchBen** [comment]
Once properly updated, Fixes https://github.com/kitematic/minecraft/pull/19

**Comment by ls-endurance** [comment]
Beautiful, i'll get to it tonight. Thanks man :)

**Comment by FrenchBen** [comment]
@ls-endurance any updates for the jar file location?

**Pull request closed without merging**
