### PR TITLE
Update for 1.12 of Minecraft

### PR DESCRIPTION
**Pull request by legodude17**
Start pulling in the 1.12 jar file instead of 1.11.2.

### CODE REVIEW

**Comment by FrenchBen** [comment]
Thanks @legodude17 for this PR - would it be too much for you to update it in order to make it more flexible?
What I have in mind is adding a variable to declare the Minecraft version we wish to download.

Something like:
```
ENV MINECRAFT_VERSION 1.12
RUN wget -q https://s3.amazonaws.com/Minecraft.Download/versions/${MINECRAFT_VERSION}/minecraft_server.${MINECRAFT_VERSION}.jar
....
CMD echo eula=true > /data/eula.txt && java -jar /minecraft_server.${MINECRAFT_VERSION}.jar
```

**Comment by legodude17** [comment]
Did what you suggested @FrenchBen. Thanks for the feedback!

**Review by FrenchBen — APPROVED** [review]
LGTM

**Comment by FrenchBen** [comment]
@legodude17 thanks for the update. 
When I try to run the Minecraft server I get the following error:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/server/MinecraftServer : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

Looks like the version of JDK will need to be updated as well - `openjdk-9-jre-headless` seems to work for me. Additionally we should probably pass the `nogui` option to the server.

**Comment by legodude17** [comment]
Ohh, right. Minecraft 1.12 introduces the requirement for Java 8. Also, surprised that `nogui` wasn't being passed before.

EDIT: Should be fixed now.

**Comment by FrenchBen** [comment]
Doesn't look like `wheezy` has JDK-8 `E: Unable to locate package openjdk-8-jre-headless`

**Comment by legodude17** [comment]
So would you suggest it be switched to Java 9?

**Comment by FrenchBen** [comment]
I think that would be fine - we can even go to an `ubuntu` base image if you'd like

**Comment by legodude17** [comment]
I think switching to `ubuntu` would be better because AFAIK Java 9 is still experimental

**Review by agentcobra — APPROVED** [review]

**Comment by FrenchBen** [comment]
@legodude17 did you ever get a chance to upgrade the image to use ubuntu?

**Comment by legodude17** [comment]
@FrenchBen Ubuntu doesn't have a good way to install Java 8 in docker that I can find. I got a version working with https://github.com/dockerfile/java

**Comment by FrenchBen** [comment]
Which ever base image gets the job done really - Feel free to update your PR accordingly and I'll confirm that it builds on my end :)

**Comment by jburger** [comment]
Hey people, I have a fork that fixes the issues in regards to JRE 8. Have confirmed it all works locally on my windows server 2016 and windows 10 client machines. Feel free to pinch the code, or if you like I can submit another PR for this.

https://github.com/jburger/minecraft/blob/master/Dockerfile

**Comment by FrenchBen** [comment]
@jburger Can you go ahead and create a PR for it and reference this one?

**Pull request closed without merging**
